#!/bin/bash -ev
pushd tlaplus
cabal sandbox init
cabal install -j
popd

pushd tlaplus-eval
cabal sandbox init
cabal sandbox add-source ../tlaplus/
cabal install -j
popd

pushd tlaplus-swimlane
cabal sandbox init
cabal sandbox add-source ../tlaplus/
cabal sandbox add-source ../tlaplus-eval/
cabal install -j
popd

pushd short
cabal sandbox init
cabal sandbox add-source ../tlaplus/
cabal install -j
popd
echo "done - all specifica modules built and installed.."
