#!/bin/bash -e
pushd tlaplus
cabal install
popd
pushd tlaplus-eval
cabal install
popd
pushd tlaplus-swimlane
cabal install
popd
pushd short
cabal install
popd
echo "done - all specifica modules built and installed.."

