name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        pwd
        ls -al
        cd tlaplus
        cabal install --only-dependencies
    - name: Build
      run: |
        pwd
        cd tlaplus
        cabal configure
        cabal build
